version: 2

workflows:
  api:
    jobs:
      - test-api

      - deploy-api:
          filters:
            branches:
              only:
                - master
          requires:
            - test-api

workflows:
  front:
    jobs:
      - test-front

      - deploy-front:
          filters:
            branches:
              only:
                - master
          requires:
            - test-front

jobs:
  test-api:
    working_directory: ~/shiftdataportal/server
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout:
          path: ~/shiftdataportal
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-yarn
          command: yarn ci
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Test
          command: yarn test
      - run:
          name: Run typescript which is the same as running a build
          command: yarn tsc

  deploy-api:
    resource_class: small
    docker:
      - image: cimg/base:2023.10
    steps:
      - checkout
          path: ~/shiftdataportal
      - run:
          name: Add Scalingo to known_hosts
          command: mkdir -p ~/.ssh && ssh-keyscan -H ssh.osc-fr1.scalingo.com >> ~/.ssh/known_hosts
      - run:
          name: Deploy on Scalingo
          command: git push git@ssh.osc-fr1.scalingo.com:data-portal-back.git master

  test-front:
    working_directory: ~/shiftdataportal/client
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout:
          path: ~/shiftdataportal
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-yarn
          command: yarn ci
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Test
          command: yarn test
      - run:
          name: Run typescript which is the same as running a build
          command: yarn build

  deploy-front:
    resource_class: small
    docker:
      - image: cimg/base:2023.10
    steps:
      - checkout
          path: ~/shiftdataportal
      - run:
          name: Add Scalingo to known_hosts
          command: mkdir -p ~/.ssh && ssh-keyscan -H ssh.osc-fr1.scalingo.com >> ~/.ssh/known_hosts
      - run:
          name: Deploy on Scalingo
          command: git push git@ssh.osc-fr1.scalingo.com:data-portal-front.git master
